### ISSUE TITLE
Generated OBJ/MTL from Blender in Cycles

### ISSUE THREAD

**Issue by spacorum** [JordanDelcros/OBJImg#4]
H, there. I´ve been trying OBJImg to generate compressed model images from my Blender designs. I managed to create the image, but when I try to load it, the mesh has a color set, but not any textures. The weird part is that I can see the texture file being loaded in the console. I think the problem must be that I´m using Cycles mode in Blender (for rendering purporses, all my models are like this).

Do you have any clue what I must do to make it work with exported models from Blender Cycles? Thanks

EDIT: When I load the original exported OBJ/MTL in Three.JS to generate the image, its material has a "map" property with the texture information. But this property is missing when loading the generated image, is null.

EDIT 2 (SOLVED!): The original exported MTL file from Blender had two materials (the first is the good one, but there´s a second one named "newmtl Material_NONE" which has no texture file associated, and it seems OBJImg tries to load the second one. I tried deleting this second material in the MTL and voilà: the texture is now loading over the mesh perfectly. I wonder if there is an option to avoid including this strange "Material_NONE" in the MTL file... Otherwise I should remember to delete it every time I export from Blender.

**Comment by spacorum** [comment]
These are my Blender export settings, by the way:
https://imgur.com/a/B8guP

-Selection only
-Apply modifiers
-Write normals
-Include UVs
-Write materials
-Triangulate faces
-Objects as OBJ Objects
-Objects as OBJ Groups

**Comment by JordanDelcros** [comment]
Hey there, sorry for the late answer but I'm not in the same GMT as yours I guess.
So, is your problem completely solved?

Thanks

**Comment by spacorum** [comment]
Yes, you can solve this manually deleting the second Material_NONE (the one without texture) in your exported MTL file. At least this worked in my case (Blender 2.78c). Important: this only works if you delete the Material_NONE just after the export in Blender, and BEFORE launching OBJImg.generateIMG(...)

Anyway, maybe it would be good if you add a couple of lines to check if the "map_Kd XXXXX.png" texture path for the material in the MTL is defined. If not, I guess you could consider that material as invalid, so OBJImg would take the first one on the list (in this case, the one named "Material", avoiding the second one, whose purpose sincerelly I don´t know):

```
# Blender MTL File: 'model.blend'
# Material Count: 2

newmtl Material
Ns 96.078431
Ka 1.000000 1.000000 1.000000
Kd 0.640000 0.640000 0.640000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2
map_Kd model.png

newmtl Material_NONE
Ns 96.078431
Ka 1.000000 1.000000 1.000000
Kd 0.640000 0.640000 0.640000
Ks 0.500000 0.500000 0.500000
Ke 0.000000 0.000000 0.000000
Ni 1.000000
d 1.000000
illum 2

```
